permalink: /archives/:year/:month/:title.html
paginate: 10
markdown: rdiscount

# 作者信息
author: 
  name: Zollty
  email: zollty@163.com
  link: http://blog.zollty.com
  weibo: http://weibo.com/zollty
  github: https://github.com/zollty

# 站点信息
title: Zollty Blog 
description: Zollty Blog
url: http://blog.zollty.com
rss_url: 

# gavatar头像及Favicon
gavatar: http://ires.qiniudn.com/avatar-50-50.jpg
favicon: http://ires.qiniudn.com/favicon.ico

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: zollty

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Docker
  - Java

# 中文本地化
locals:
  tags: 标签
  about: 关于
  archive: 归档
  newest: 最新文章
